FROM ruby:3

RUN apt-get update && apt-get install vim -y

RUN useradd -m builder
RUN mkdir -p /workdir/backend
RUN chown -R builder /workdir

WORKDIR /workdir/backend

COPY ./Gemfile* ./
RUN bundle install
RUN chmod -R 777 /usr/local/bundle/*
COPY . .

COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

EXPOSE 3000

CMD ["/bin/bash"]
